# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2fa92ff19e946836d067bfef93ebaefd959436b1ad94f8afd41b834424e4cd4331c2c519d4e1ddc26fb800b22d0c8cb0bb8f121620b0c4d35d98e6d0ef1e6cb9

test:
  secret_key_base: 3d8eb96ede35f31378be865e9c5a900abc0c129ad17319cc9b55b8d4c53d5d2319266ee7d8efe248b29c752be6db61d98cd481db8283bd75e60d226809357e52

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
